name: Create S3 bucket
on:
  push:
    branchs:
    - main
    - release

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terrafrom:
    name: terrafrom
    runs-on: ubuntu-latests
    env:
      AWS_IAM_ROLE: ${{ secrets.AWS_IAM_ROLE }}
      AWS_REGION: us-east-1
    steps:
      - name: Checkout Source
      - user: actions/checkout@v3

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Test AWS Credential
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

