pipeline {
    agent any

    stages {
        stage('terraform') {
            steps {
                bat '''
                  terraform init
                  terraform plan
                '''
            }
        }
    }
}
