pipeline {
    agent any

    stages {
        stage('terraform') {
            steps {
                dir('ssm/parameter_store'){
                  bat '''
                    terraform init
                    terraform plan
                  '''
                }
            }
        }
    }
}
