name: Create S3 bucket

on:
  push:
    branchs:
    - main
    - release

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terrafrom:
    name: terrafrom
    runs-on: ubuntu-latests
    # env:
    #   AWS_IAM_ROLE: ${{ secrets.AWS_IAM_ROLE }}
    #   AWS_REGION: us-east-1
    defaults:
      run:
        working-directory: s3
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::287243894258:role/gitaction-iam-ssm-lambda-role #${{ env.AWS_IAM_ROLE }}
          aws-region: us-east-1  #${{ env.AWS_REGION }}
      
      - name: Test AWS Credential
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

